### PR TITLE
Add WIP stub for the math module (demonstrative - low priority)

### PR DESCRIPTION
**Pull request by 0joshuaolson1**

### CODE REVIEW

**Comment by farskipper** [comment]
Looks good! Except it should use the native node.js [crypto](https://nodejs.org/api/crypto.html#crypto_class_hash)  module instead of jshashes.

**Comment by 0joshuaolson1** [comment]
That oughta do it.

**Comment by farskipper** [comment]
So I wouldn't worry much about the try/catch around `require("crypto")` Since we only support node 4+. Those node.js built-in modules are part of the node binary, there not in the package.json or anything.

Travis/appveyor run tests against all the versions of node we support so we'll easily know if it needs a work-around. But the core node api's are pretty stable, especially since node 4

I added `math:sha2` as a crypto example. (although if you wanted to get crazy you could use the streaming api which may be faster)

Also `base64decode` doesn't return "" for invalid base64. For example try `"hello!"` node.js Buffer decodes base64 on a best effort basis, so it decodes `"hello"` and ignores `"!"`. Anyways just test some invalid input and decide how you want to handle it.

**Comment by 0joshuaolson1** [comment]
> base64decode doesn't return "" for invalid base64
Good catch.

> Those node.js built-in modules are part of the node binary

My concern is that people can build or use custom Node binaries (using e.g. v4's code), especially for poorly supported processors. Is that a realistic anticipation?

**Comment by farskipper** [comment]
No, I don't think we need worry about that. `"crypto"` `"http"` `"fs"` are all baked in and part of node, i.e. if you have node, you have those. Without those (and libuv), you just have plain-old v8. There are pre-built node binaries for arm so running on the raspberry pi for example is not an issue.

Of course if someones doing something really crazy with a custom built node binary they can cross that bridge when they get there. There are other ways to fallback. i.e. browserify has stubs for these node-apis that work in browsers.

**Comment by 0joshuaolson1** [comment]
See https://github.com/Picolab/pico-engine/pull/315 instead

**Pull request closed without merging**
